# Generated by Django 4.0 on 2023-07-07 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_applicant_faculty_rename_data_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='lastname',
            new_name='Designation',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='entrynumber',
            new_name='EmpCode',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='guardianfirstname',
            new_name='Family',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='firstname',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='guardianlastname',
            new_name='Relation',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='gender',
            new_name='sex',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='gender',
            new_name='sex',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='hostel',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='roomnumber',
        ),
    ]
