# Generated by Django 4.0 on 2023-07-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_rename_lastname_faculty_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='form_type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
