# Generated by Django 4.0 on 2023-07-08 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_alter_student_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sex',
        ),
    ]
