# Generated by Django 4.0 on 2023-07-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_remove_student_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='M', max_length=100),
        ),
    ]
