# Generated by Django 4.0 on 2023-07-08 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_student_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='sex',
            new_name='gender',
        ),
    ]
