# Generated by Django 4.0 on 2023-07-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_rename_sex_faculty_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='gender',
            field=models.CharField(max_length=100),
        ),
    ]
