# Generated by Django 4.2 on 2023-07-07 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_transaction_checksum_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='checksum_after',
            new_name='PGtransactionID',
        ),
    ]
